name: 🚀 Publish Node.js Package to GitHub

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 📚 Checkout
        uses: actions/checkout@v2
      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: ✏️ Change name
        uses: deef0000dragon1/json-edit-action/@v1
        env:
          KEY: name
          VALUE: '@kamack38/solve3-cli'
          FILE: package.json
      - name: 📦 Install dependencies
        run: npm i
      - name: 🔧 Build package
        run: npm run build
      - name: 🚀 Publish to GitHub Packages
        run: npm publish --registry https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_PAT}}
